name: Deno CI

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Cache Deno modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
          key: ${{ runner.os }}-deno-${{ hashFiles('src/**/deps.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31
        with:
          deno-version: '1.40.0'

      - name: Verify formatting
        run: deno fmt --check
        working-directory: src

      - name: Run linter
        run: deno lint
        working-directory: src
